spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093,localhost:9094
      bindings:
        messages_in:
          group: stream-listener-group
          destination: t_messages